### ISSUE TITLE
Chaturbate is missing favorites

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#1210]
Chaturbate is missing favorites tab.

**Comment by jegfonseca** [comment]
to me neither

**Comment by karci78** [comment]
And when you add an item to the main menu, they don't work, plugin error

**Comment by dobbelina** [comment]
[chaturbate enable online favourites menu fix](https://github.com/dobbelina/repository.dobbelina/commit/a786e80f89ccf98637a9366681be6d7c5b26f2e7)
Will be in the next release Version 1.1.93

**Comment by jegfonseca** [comment]
Thanks

**Comment by karci78** [comment]
I have still problem..when I add item (from tags-female,Anal or else) to main menu or custom menu, they dont work,error.
I create custom list "chaturbate" and in is Tags- Couples,females-Pregnant , females-bdsm , females-fuckmashines ... This tags dont work.

**Comment by karci78** [comment]
2023-10-29 18:36:09.897 T:11236   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 173, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 160, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 128, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\chaturbate.py", line 126, in List
                                                       listhtml = json.loads(listhtml)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

**Comment by karci78** [comment]
2023-10-29 18:36:09.897 T:11236   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 173, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 160, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 128, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\chaturbate.py", line 126, in List
                                                       listhtml = json.loads(listhtml)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2023-10-29 18:36:09.964 T:8708    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.cumination/?channel=None&keyword=Couple&mode=chaturbate.List&name=%5bCOLOR%20hotpink%5dChaturbate%5b%2fCOLOR%5d%5bCOLOR%20white%5d%20-%20webcams%5b%2fCOLOR%5d%20-%20%5bCOLOR%20violet%5dCouple%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fchaturbate.com%2fcouple-cams%2f%3fpage%3d1
2023-10-29 18:36:09.967 T:8680    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/?channel=None&keyword=Couple&mode=chaturbate.List&name=%5bCOLOR%20hotpink%5dChaturbate%5b%2fCOLOR%5d%5bCOLOR%20white%5d%20-%20webcams%5b%2fCOLOR%5d%20-%20%5bCOLOR%20violet%5dCouple%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fchaturbate.com%2fcouple-cams%2f%3fpage%3d1) failed
2023-10-29 18:36:14.130 T:8680     info <general>: Stopping the application...
2023-10-29 18:36:14.130 T:8680     info <general>: Stopping player

**Comment by Gujal00** [comment]
Do no post log snippets, upload the full unedited debug log as per instructions to paste.kodi.tv and then provide the link for the paste here
