### ISSUE TITLE
Cumination error  

### ISSUE THREAD

**Issue by 450CATman** [dobbelina/repository.dobbelina#1237]
leia 18.7 wont open have updated to 1.1.96 same issue as of 11/25/2023

**Comment by ErosVece** [comment]
Try this fix: https://github.com/dobbelina/repository.dobbelina/commit/78310a365ff5036521b66b209f170eaa82b20b6f

**Comment by pitsi** [comment]
The (non-debug) log with the issue. It's the first time that I post a log AFTER a patch is available :D 
I just patched it and it works :) 
Thank you for fixing all those python2 issues for all of us that can not use a python3 version of kodi.
```
2023-11-27 18:06:16.552 T:139868319459072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: Non-ASCII character '\xc3' in file /storage/.kodi/addons/plugin.video.cumination/resources/lib/sites/thepornfull.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (thepornfull.py, line 51)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.cumination/default.py", line 33, in <module>
                                                from resources.lib.sites import *  # noqa
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/sites/thepornfull.py", line 51
                                            SyntaxError: Non-ASCII character '\xc3' in file /storage/.kodi/addons/plugin.video.cumination/resources/lib/sites/thepornfull.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
                                            -->End of Python script error report<--
2023-11-27 18:06:16.677 T:139868386600704   ERROR: GetDirectory - Error getting plugin://plugin.video.cumination/
2023-11-27 18:06:16.683 T:139869715171456   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/) failed

```

**Comment by Gary7777** [comment]
Same issue as Catman, but using 18.9 on a firestick. nyway this can be fixed or patched?
Thank you

**Comment by Gary7777** [comment]
![112723170916](https://github.com/dobbelina/repository.dobbelina/assets/20507819/34d1f1d9-b3a5-49b2-94ca-dc0479629ee7)
![112723170916](https://github.com/dobbelina/repository.dobbelina/assets/20507819/d770edec-dc6a-497c-a696-474d441d25c6)

**Comment by Gary7777** [comment]
![112723170916](https://github.com/dobbelina/repository.dobbelina/assets/20507819/a871a8c7-e3bc-4d9f-8723-534c19dc3dab)

**Comment by ErosVece** [comment]
>  Same issue as Catman, but using 18.9 on a firestick. anyway this can be fixed or patched? Thank you

It has been fixed or patched....read my comment.
