### ISSUE TITLE
Beeg not working on UWC Scenes

### ISSUE THREAD

**Issue by TokeRider** [dobbelina/repository.dobbelina#178]
Here is the log file snippet relevant to Beeg not working:

2020-02-09 20:36:24.069 T:18360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\default.py", line 214, in <module>
                                                sys.exit(main())
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\default.py", line 208, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 59, in BGMain
                                                BGList('https://beeg.com/api/v6/'+bgversion+'/index/main/0/pc')
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 74, in BGList
                                                title = replaceunicode(video["title"])
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 134, in replaceunicode
                                                unicodechar = re.compile(r'\\u(....)').findall(str)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
2020-02-09 20:36:24.234 T:4932   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.uwc/?channel=None&keyword&mode=80&name=%5bCOLOR%20hotpink%5dBeeg%5b%2fCOLOR%5d&page&section=None&url=http%3a%2f%2fbeeg.com%2fpage-1
2020-02-09 20:36:24.256 T:648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/?channel=None&keyword&mode=80&name=%5bCOLOR%20hotpink%5dBeeg%5b%2fCOLOR%5d&page&section=None&url=http%3a%2f%2fbeeg.com%2fpage-1) failed

**Comment by 12asdfg12** [comment]
fixed
