### ISSUE TITLE
Beeg in Whitecream Scenes not working

### ISSUE THREAD

**Issue by TokeRider** [dobbelina/repository.dobbelina#239]
Beeg in Whitecream Scenes is not working.  Here is the relevant error from the kodi.log file:

2020-05-19 18:26:31.409 T:11880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\default.py", line 217, in <module>
                                                sys.exit(main())
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\default.py", line 211, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 54, in BGMain
                                                BGVersion()
                                              File "C:\Users\Nelson\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 43, in BGVersion
                                                bgversion = re.compile(r"var beeg_version = (\d+);", re.DOTALL | re.IGNORECASE).findall(bgpage)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-05-19 18:26:31.528 T:5940   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.uwc/?channel=None&keyword&mode=80&name=%5bCOLOR%20hotpink%5dBeeg%5b%2fCOLOR%5d&page&section=None&url=http%3a%2f%2fbeeg.com%2fpage-1
2020-05-19 18:26:31.531 T:7192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/?channel=None&keyword&mode=80&name=%5bCOLOR%20hotpink%5dBeeg%5b%2fCOLOR%5d&page&section=None&url=http%3a%2f%2fbeeg.com%2fpage-1) failed

**Comment by dobbelina** [comment]
Thanks for reporting , issue confirmed.
Also Woxtube and Eroticage are down.

**Comment by 12asdfg12** [comment]
quickfix for beeg:
replace lines 54 and 55 from beeg.py
```
    BGVersion()
    bgversion = addon.getSetting('bgversion')
```
with:
```
    bgversion = '1589461492752'
```

**Comment by dobbelina** [comment]
Thanks for the heads up 12asdfg12!
Beeg just started working again without the fix.
