### ISSUE TITLE
[Question] ffmpeg - error on cam streams download

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#360]
Guys, I'm sorry to bother you, but I don't understand what I'm doing wrong. 

On Windows I set the path for ffmpeg, as well as a download folder path. --> everything works fine. 

On Raspberry Pi 2 (Libreelec) I use  /storage/.kodi/addons/tools.ffmpeg-tools/bin/ffmpeg --> Start the stream --> Error (no download) / but stream is running.

Did I use the completely wrong files here?

Log:

2020-12-05 18:43:58.349   WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
2020-12-05 18:44:01.443   WARNING: Attempt to use invalid handle -1
2020-12-05 18:44:03.641   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'STARTUPINFO'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 234, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 228, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/chaturbate.py", line 248, in Playvid
                                                if addon.getSetting("dwnld_stream")=="true" or download==1: utils.dwnld_stream(videourl, username)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/utils.py", line 1239, in dwnld_stream
                                                info = subprocess.STARTUPINFO()
                                            AttributeError: 'module' object has no attribute 'STARTUPINFO'
                                            -->End of Python script error report<--
2020-12-05 18:44:04.022 T:1937231888  NOTICE: VideoPlayer::OpenFile: https://edge278.stream.highwebmedia.com/live-hls/amlst:blonde_riderxxx-sd-14d03049b98b333f6f3d02877a451f442d39995f4b932fde8ad4efd5b88fc03b_trns_h264/playlist.m3u8
2020-12-05 18:44:04.081  NOTICE: Creating InputStream
2020-12-05 18:44:04.553  NOTICE: Creating Demuxer
2020-12-05 18:44:10.948  NOTICE: Opening stream: 10 source: 256
2020-12-05 18:44:13.588  NOTICE: Creating video codec with codec id: 27
2020-12-05 18:44:13.607  NOTICE: Creating video thread
2020-12-05 18:44:13.608  NOTICE: running thread: video_thread
2020-12-05 18:44:13.740  NOTICE: Opening stream: 11 source: 256
2020-12-05 18:44:13.741  NOTICE: Finding audio codec for: 86018
2020-12-05 18:44:13.745  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac

**Comment by camilt** [comment]
Check the #357

**Comment by joselbcn36** [comment]
Hi there, love there is an option to download from webcams, but one question.

I have ubuntu with kodi, and installed fffmeg  with the following comands:

sudo apt update

sudo apt install ffmpeg

The verify it is installed : 

ffmpeg -version

Results: fmpeg version 4.2.4-

Then for check the folder:

locate ffmpeg

it shows that the path is : /usr/share/ffmpeg

Set in the plugin as path for ffmeg, but when i try to download it displays a message as i have to be sure about permissions or something like that.

Can you point me how to download webcams videos in ubuntu computer?
