### ISSUE TITLE
Updated to 1.2.38 --> still no cam download using ffmpeg (Libreelec)

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#365]
Sry, to bother you again. I have updated the UWC version to 1.2.38 and now I get another error when I try to start downloading streams. I do not know if I use the wrong files. ... they are the official ffmpeg from Libreelec. I use Kodi 18.9 on Raspberry Pi 2. On Windows everything works perfectly!

/storage/.kodi/addons/tools.ffmpeg-tools/bin/ffmpeg

Log: 

2020-12-10 12:57:39.268 T:1313383296 WARNING: Attempt to use invalid handle -1
2020-12-10 12:57:40.170 T:1313383296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 234, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 228, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/chaturbate.py", line 248, in Playvid
                                                if addon.getSetting("dwnld_stream")=="true" or download==1: utils.dwnld_stream(videourl, username)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/utils.py", line 1244, in dwnld_stream
                                                proc = subprocess.Popen(cmd, shell=False, startupinfo=info)
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                            OSError: [Errno 2] No such file or directory
                                            -->End of Python script error report<--
2020-12-10 12:57:40.666 T:1937391632  NOTICE: VideoPlayer::OpenFile: https://edge88.stream.highwebmedia.com/live-hls/amlst:little_flower_-sd-91252e5138966cf1ddcb0c11ca5eff4fff9dbb4d543ff58e8b18e44a38bba30a_trns_h264/playlist.m3u8
2020-12-10 12:57:40.725 T:1483031424  NOTICE: Creating InputStream
2020-12-10 12:57:41.001 T:1483031424  NOTICE: Creating Demuxer

**Comment by ldca58** [comment]
I have exactly the same problem. Working on Windows, but not on Libreelec (same errors as @Kodionpi ).

**Comment by jdoedev123** [comment]
Not sure about Windows problems but posted this in a thread about stream download problems on Ubuntu which should apply to Libreelec on Pi too:

"Their are bugs for Linux in the download code.
1)For Linux the code should be:
proc = subprocess.Popen(cmd, shell=True, startupinfo=info)
not:
proc = subprocess.Popen(cmd, shell=False, startupinfo=info)
as in the present utils.py code.
2) It is sensitive to where the ffmpeg binary is. It does not like "Location of ffmpeg" being in a normal system directory such as /bin which is common on most Linux's. The "Location of ffmpeg" directory needs to have write permission for the user.
3) It is sensitive to where the output file is on the network. ffmpeg does not like the Download Directory directly on an NFS connection. But it is ok with an NFS drive mounted to the local filesystem."

**Comment by Kodionpi** [comment]
I changed  shell=False  to  shell=True  and it worked! Thanks a lot @jdoedev123 !!!

**Comment by ldca58** [comment]
Thanks @jdoedev123! Changing shell=False to shell=True fixed it for me to.

**Comment by jdoedev123** [comment]
@ldca58  and @Kodionpi  The bug must be in both Windows and Linux. Thanks for checking back in. I have personally not tested on Windows or my Pi 2 or Pi 3 (I have a lot of Pi's) with Libreelec. Too many versions and platforms to support without feedback from the community.

**Comment by onknight** [comment]
Will I run Windows  So I can test there

**Comment by ldca58** [comment]
I did a quick test on Windows.

With shell=False, Kodi crashes as soon as I start to download. Strangely, it downloads and saves the stream, even though Kodi is no longer running.

When I changed it to shell=True, Kodi did not crash any more, and it seems to be working correctly.

**Comment by jdoedev123** [comment]
@dobbelina  This fix was not in 1.2.39. 
utils.py  line 1244 currently: 
    proc = subprocess.Popen(cmd, shell=False, startupinfo=info)
Tested fix on Linux and Windows:
    proc = subprocess.Popen(cmd, shell=True, startupinfo=info)

**Comment by dobbelina** [comment]
@jdoedev123 sorry i missed it, will be in next update Version 1.2.40
https://github.com/dobbelina/repository.dobbelina/commit/a8c1c3ec0576e2ca61d1fb0ad2e06168aa7e3323
