### ISSUE TITLE
[Bug] Pornhub not working

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#369]
Pornhub Videos are not working. Neither on Windows nor on Libreelec.

Log:

2020-12-13 23:32:57.522 T:1248846720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 234, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 228, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/pornhub.py", line 92, in Playvid
                                                videolink = match[0][1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by jdoedev123** [comment]
They are probably in the middle of changing the website. I have some experimental code which was not working and then suddenly worked and some of their code said "experimental". So rather than do an endless chase as we both change it is best to let it settle for a few days.
In any case, my experimental code moved the playback resoloving to SMR.xxx so it should work for all similar Kodi plugins.

**Comment by jdoedev123** [comment]
Update: I don't know if it is related but the news reports PornHub has/is doing a major website revamp. From Pornhub's blog:
"We banned unverified uploaders from posting new content, eliminated downloads..."
This may take awhile to settle on the website.
