### ISSUE TITLE
Kodi error - looks like this website is down 

### ISSUE THREAD

**Issue by decosse** [dobbelina/repository.dobbelina#382]
Help please?
When attempting to open the addon get error message saying looks like website is down 
It seems to be some local conflict since I don't see this being reported as a widespread issue - however I'm getting same failure on two separate systems, one Windows, one Android (although the configured Kodi is virtually same on both)  
I just installed on another machine and no error 
Tried deleting app and re-installing and still same 

This is the error log:
 
2020-12-22 15:05:32.298 T:13360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'response' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Ken\AppData\Roaming\Kodi\addons\plugin.video.uwc\default.py", line 30, in <module>
                                                from resources.lib.sites import *
                                              File "C:\Users\Ken\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 44, in <module>
                                                bgversion = BGVersion()
                                              File "C:\Users\Ken\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\beeg.py", line 36, in BGVersion
                                                bgpage = utils.getHtml('https://beeg.com','')
                                              File "C:\Users\Ken\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\utils.py", line 455, in getHtml
                                                if response: response.close()
                                            UnboundLocalError: local variable 'response' referenced before assignment
                                            -->End of Python script error report<--
2020-12-22 15:05:32.437 T:4584   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.uwc/
2020-12-22 15:06:23.001 T:20868   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/) failed

**Comment by camilt** [comment]
First, check your internet connection. This is happening when open UWC with no internet connection. It tries to open beeg.com to check the version. I'll try tomorrow to modify.

**Comment by decosse** [comment]
Thanks for quick response! 
Internet is fine (I have very fast service) and connected via direct ethernet to router  - tried with and without vpn & even momentarily disabled firewall and still same 
Odd that the third system install - just to check - opened without issue (same isp via same router)

**Comment by camilt** [comment]
#383

**Comment by dobbelina** [comment]
@decosse 
You can replace the file with this attached one until we update next time.
[beeg.zip](https://github.com/dobbelina/repository.dobbelina/files/5733533/beeg.zip)

**Comment by decosse** [comment]
Amazing support - thank you - worked perfectly!
