### ISSUE TITLE
Beeg broke uwc completely on the last day of 2020!

### ISSUE THREAD

**Issue by pitsi** [dobbelina/repository.dobbelina#388]
So, I tried launching uwc a few hours ago and it failed with this in the log
```
2020-12-31 16:58:44.562 T:139727795992320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 30, in <module>
                                                from resources.lib.sites import *
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/beeg.py", line 44, in <module>
                                                bgversion = BGVersion()
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/beeg.py", line 37, in BGVersion
                                                jsversion = re.compile(r"link href=(\/js\/app.+?.js) rel", re.DOTALL | re.IGNORECASE).findall(bgpage)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-12-31 16:58:44.674 T:139727829563136   ERROR: GetDirectory - Error getting plugin://plugin.video.uwc/
2020-12-31 16:58:44.680 T:139729270831232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/) failed
```
I am no expert, I am also completely clueless when it comes to coding, but I think beeg changed something on it's site and broke uwc. Any suggestions are welcome. Kodi 18.9 on libreelec 9.2.6 x64.

Happy 2021 to all :)

---edit
Quick and dirty solution.
Removing /storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/beeg.py (and beeg,pyo) makes uwc work again

**Comment by dobbelina** [comment]
Addon updated 2020-12-31.
Not gonna let it stay broken until next year 😄 
Beeg is still not working though.

**Comment by dobbelina** [comment]
@pitsi 
Addon updated 2020-12-31.
Not gonna let it stay broken until next year 😄 
Beeg is still not working though.

**Comment by onknight** [comment]
Yes i saw it not working    Wanted to watch some cam sites and it UWC would not launch

**Comment by jdoedev123** [comment]
My quick and dirty was add this line:
bgversion = '1595400363153'
comment out this line:
# bgversion = BGVersion()

**Comment by pitsi** [comment]
Thank you for the really quick fix! 2021 started great :D 

Correct me if I am wrong on the following. The addon checks all the providers at launch, right? And when one fails, it does not start at all. How about making it ignore the one(s) that fail and simply pop up a notification saying something like "beeg failed to respond, so it will be disabled", and simply gray it out?

**Comment by onknight** [comment]
Neat Idea Pitsi

**Comment by pitsi** [comment]
Since uwc is working again with no (major) issues, I am closing this one.
