### ISSUE TITLE
HTTP Error 403: Forbidden for PornTrex

### ISSUE THREAD

**Issue by hstegeman** [dobbelina/repository.dobbelina#511]
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label10) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label11) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label12) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label13) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label14) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label15) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label16) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label17) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label18) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label19) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label20) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label21) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label22) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label23) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label24) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label25) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label26) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label27) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label28) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label29) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label3) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label30) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label31) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label32) was not found.
2021-05-10 21:43:08.911 T:9436    DEBUG <CSettingsManager>: requested setting (label33) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label34) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label35) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label36) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label37) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label38) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label39) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label4) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label40) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label41) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label42) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label43) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label44) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label45) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label46) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label47) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label48) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label49) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label5) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label50) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label51) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label52) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label53) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label54) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label55) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label56) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label57) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label58) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label59) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label6) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label60) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label61) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label62) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label63) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label64) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label65) was not found.
2021-05-10 21:43:08.912 T:9436    DEBUG <CSettingsManager>: requested setting (label66) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label67) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label68) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label69) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label7) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label70) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label71) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label72) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label73) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label74) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label75) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label76) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label77) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label78) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label79) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label8) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label80) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label81) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label82) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label83) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label84) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label85) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label86) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label87) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label88) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label89) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label9) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label90) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label91) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (label92) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (pt_category) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptinfovideos) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptlogged) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptpass) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptplaylistsort) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptquality) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptrange) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptsort) was not found.
2021-05-10 21:43:08.913 T:9436    DEBUG <CSettingsManager>: requested setting (ptuser) was not found.
2021-05-10 21:43:08.914 T:9436    DEBUG <CSettingsManager>: requested setting (pincode) was not found.
2021-05-10 21:43:08.914 T:9436    DEBUG <CSettingsManager>: requested setting (logintime) was not found.
2021-05-10 21:43:09.019 T:9436    DEBUG <general>: HTTP Error 403: Forbidden
2021-05-10 21:43:09.032 T:7072    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-05-10 21:43:09.101 T:9436    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: expected string or bytes-like object
                                                   Traceback (most recent call last):
                                                     File "C:\kodimatrix\Kodi\portable_data\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "C:\kodimatrix\Kodi\portable_data\addons\plugin.video.cumination\default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\kodimatrix\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 126, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\kodimatrix\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\sites\porntrex.py", line 87, in PTList
                                                       match = re.compile(r'class="video-.+?data-src="([^"]+)".+?/ul>(.+?)title.+?class="quality">([^<]+).+?clock-o"></i>\s*([^<]+).+?href="([^"]+).+?>([^<]+)</a>.+?li>([^<]+)<', re.DOTALL | re.IGNORECASE).findall(listhtml)
                                                   TypeError: expected string or bytes-like object
                                                   -->End of Python script error report<--
                                                   
2021-05-10 21:43:09.101 T:9436    DEBUG <general>: CPythonInvoker::onExecutionDone(15, C:\kodimatrix\Kodi\portable_data\addons\plugin.video.cumination\default.py)
2021-05-10 21:43:09.113 T:9436    DEBUG <general>: .
2021-05-10 21:43:09.133 T:9436     INFO <general>: Skipped 1 duplicate messages..
2021-05-10 21:43:09.133 T:9436     INFO <general>: Python interpreter stopped
2021-05-10 21:43:09.133 T:9436    DEBUG <general>: Thread LanguageInvoker 9436 terminating
2021-05-10 21:43:09.140 T:9428    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.cumination/?category=None&channel=None&filtered=None&hash=None&keyword&longer=None&loop=None&mode=porntrex.PTList&name=%5bCOLOR%20hotpink%5dSubscription%20videos%5b%2fCOLOR%5d&onelist=None&page=1&quality=None&reverse=None&section=None&sort=None&url=https%3a%2f%2fwww.porntrex.com%2fmy%2fsubscriptions%2f%3fmode%3dasync%26function%3dget_block%26block_id%3dlist_videos_videos_from_my_subscriptions%26sort_by%3d%26from_my_subscriptions_videos%3d1&username=None&writefile=None
2021-05-10 21:43:09.140 T:9428    DEBUG <general>: Thread waiting 9428 terminating
2021-05-10 21:43:09.148 T:7072    DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------

The exception line code in PTList doesn't seam to work all the time:

    except urllib_error.HTTPError as e:
        if e.code == 403:

My tempory workaround is to logout, and to login again, but in my opinion the python code should recognize the 403 error, well it doesn't.

### OS environment
Windows 8.1, Device, Laptop Acer i7.

**Comment by hstegeman** [comment]
try:
        listhtml = utils.getHtml(url, site.url, headers=hdr)
        if not listhtml:
            print('no listhtml')

<result>
2021-05-10 22:07:22.059 T:10136   DEBUG <general>: no listhtml

listhtml doesn't exist without giving an error, strange....

    except urllib_error.HTTPError as e:
        if e.code == 403:
            if PTLogin(False):
                hdr['Cookie'] = get_cookies()
                listhtml = utils.getHtml(url, site.url, headers=hdr)

**Comment by hstegeman** [comment]
I think the next code is a... solution:
    try:
        listhtml = utils.getHtml(url, site.url, headers=hdr)
        if not listhtml:
            print('no listhtml')
            PTLogin(logged=False)
            hdr['Cookie'] = get_cookies()
            listhtml = utils.getHtml(url, site.url, headers=hdr)
    except urllib_error.HTTPError as e:
        if e.code == 403:
            if PTLogin(False):
                hdr['Cookie'] = get_cookies()
                listhtml = utils.getHtml(url, site.url, headers=hdr)

**Comment by hstegeman** [comment]
Perhaps the next code is a solution:
<cut>
    hdr = dict(utils.base_hdrs)
    hdr['Cookie'] = get_cookies()
    try:
        listhtml = utils.getHtml(url, site.url, headers=hdr)
        if not listhtml:
            print('no listhtml')
            PTLogin(logged=False)
            hdr['Cookie'] = get_cookies()
            listhtml = utils.getHtml(url, site.url, headers=hdr)
    except urllib_error.HTTPError as e:
        if e.code == 403:
            if PTLogin(False):
                hdr['Cookie'] = get_cookies()
                listhtml = utils.getHtml(url, site.url, headers=hdr)

**Comment by hstegeman** [comment]
The tabs are not visible, I don't like github...

**Comment by hstegeman** [comment]
I don't think that my solution is the final solution, 
e.code == 403 should solve the problem, it still doesn't.
My tempory solution is only a workaround.

**Comment by ErosVece** [comment]
```
2021-05-10 21:43:08.913 T:9436 DEBUG : requested setting (pt_category) was not found.
2021-05-10 21:43:08.913 T:9436 DEBUG : requested setting (ptinfovideos) was not found.
2021-05-10 21:43:08.913 T:9436 DEBUG : requested setting (ptplaylistsort) was not found.
2021-05-10 21:43:08.913 T:9436 DEBUG : requested setting (ptquality) was not found.
2021-05-10 21:43:09.019 T:9436 DEBUG : HTTP Error 403: Forbidden
```
I'm curious where those settings are coming from, do you have a modded porntrex.py? :)
The ones like ptinfovideos and ptplaylistsort are not in Cumination.

About the 403, I can't replicate it, I always get my subscription videos.

**Comment by hstegeman** [comment]
I have a modded porntrex_lullo777.py version, but I also see the problem with the original porntrex.py.
I did add playlists, members and countless of all kind of other stuff. But It  isn't fool proof.

I also have my own version of addDir in basic.py and I did add_dir2 to url_dispatcher.py to make use of more arguments that I want to use in my own version of porntrex.

<snip begin>I think I know what's going on, I think it will be fixed in a next update ;)<snip end>
I am looking forward to your solution.

**Comment by ErosVece** [comment]
Care to share your additions from the 'Jiskefet' version? ;)
I think Team Cumination can work them into Cumination.

You can upload the py's here.

**Comment by hstegeman** [comment]
I did add my code to a fork.
See update porntrex_lullo777.py
https://github.com/hstegeman/repository.dobbelina/commit/e3f4be100c8090794c2ac1ef9a5bef90afb07872

**Comment by hstegeman** [comment]
No response and no help, I did add my code with no response, thank you NOT.

**Comment by ErosVece** [comment]
This should have been fixed with https://github.com/dobbelina/repository.dobbelina/commit/1a554e9f50daede08137e9989c50967a0c06016e

You're welcome!!
