### ISSUE TITLE
PeekVids search function

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#580]
Hello Cumination Team, thanks for your great work! 

PeekVids search function is not working.

Log:
 ERROR: GetDirectory - Error getting plugin://plugin.video.cumination/?channel=None&keyword=riley%20reid&mode=peekvids.Search&name=%5bCOLOR%20deeppink%5driley%20reid%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fwww.peekvids.com%2fsq%3fq%3d
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/?channel=None&keyword=riley%20reid&mode=peekvids.Search&name=%5bCOLOR%20deeppink%5driley%20reid%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fwww.peekvids.com%2fsq%3fq%3d) failed
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.cumination/default.py", line 155, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.cumination/default.py", line 148, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/url_dispatcher.py", line 115, in dispatch
                                                cls.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/sites/peekvids.py", line 87, in Search
                                                List(url)
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/sites/peekvids.py", line 36, in List
                                                listhtml = utils.getHtml(url, site.url)
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/utils.py", line 399, in getHtml
                                                return cache.cacheFunction(_getHtml, url, referer, headers, NoCookie, data, error)
                                              File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.cumination/resources/lib/utils.py", line 420, in _getHtml
                                                response = urlopen(req, timeout=30)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.cumination/?channel=None&keyword=riley%20reid&mode=peekvids.Search&name=%5bCOLOR%20deeppink%5driley%20reid%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fwww.peekvids.com%2fsq%3fq%3d
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/?channel=None&keyword=riley%20reid&mode=peekvids.Search&name=%5bCOLOR%20deeppink%5driley%20reid%5b%2fCOLOR%5d&page=None&section=None&url=https%3a%2f%2fwww.peekvids.com%2fsq%3fq%3d) failed

[kodilog.txt](https://github.com/dobbelina/repository.dobbelina/files/6991733/kodilog.txt)

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/89190eadc254b97c50584f503d18abe4ca220ff2
