### ISSUE TITLE
Cumination Herexxx videos featuring korean/japan text do not play

### ISSUE THREAD

**Issue by TapeMeOh** [dobbelina/repository.dobbelina#638]
Hello. I have found that when trying to watch a video on cumination from the herexxx website that videos which include korean or japanese text characters do not play with the error 'it looks like this website is down' been displayed.

i'm not sure if it is an issue with the addon or maybe something else on my setup which is kodi 19.2 on a windows 10 64-bit pc.

Here is a part of the log file where the error shows.

>  
                                                   Error Type: <class 'UnicodeEncodeError'>
                                                   Error Contents: 'latin-1' codec can't encode characters in position 26-27: ordinal not in range(256)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 115, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\herexxx.py", line 95, in Playvid
                                                       html = utils.getHtml(iframe, url)
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\utils.py", line 398, in getHtml
                                                       return cache.cacheFunction(_getHtml, url, referer, headers, NoCookie, data, error)
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 628, in cacheFunction
                                                       ret_val = funct(*args)
                                                     File "C:\Users\stefm\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\utils.py", line 419, in _getHtml
                                                       response = urlopen(req, timeout=30)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 525, in open
                                                       response = self._open(req, data)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 542, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 1393, in https_open
                                                       return self.do_open(http.client.HTTPSConnection, req,
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 1350, in do_open
                                                       h.request(req.get_method(), req.selector, req.data, headers,
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1255, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1296, in _send_request
                                                       self.putheader(hdr, value)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1228, in putheader
                                                       values[i] = one_value.encode('latin-1')
                                                   UnicodeEncodeError: 'latin-1' codec can't encode characters in position 26-27: ordinal not in range(256)
                                                   -->End of Python script error report<--
                                                   
2021-11-08 01:55:33.301 T:13968    INFO <general>: Python interpreter stopped

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/02464cd3cf833a5bfe448241c46b1c8800118dcf
