### ISSUE TITLE
Can’t skip ahead on perverzija

### ISSUE THREAD

**Issue by Dbears0520** [dobbelina/repository.dobbelina#646]
Other sites allow skip function on Kodi but  this one doesn’t seem to work

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by imurreflection** [comment]
I am also facing this issue..I thought I am the only one..no such issue observed on mobile or PC browser..please fix it

**Comment by ErosVece** [comment]
As far as I can see, it's an issue with Kodi, not Cumination.

**Comment by disha9551** [comment]
Its only issue in this site only in others the player is working fine.

**Comment by dobbelina** [comment]
A fix will be in the next 1.1.43 release https://github.com/dobbelina/repository.dobbelina/commit/7022e1f7bb1f1efa07536fbc29ad59a0405ffb57

**Comment by dobbelina** [comment]
I have a problem with the fix.
```
Error Contents: None object cannot be quoted
                                            Traceback (most recent call last):
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                sys.exit(main())
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 148, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 119, in dispatch
                                                cls.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\perverzija.py", line 110, in Play
                                                m3u8html = utils.getHtml(videourl, iframeurl)
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\utils.py", line 399, in getHtml
                                                return cache.cacheFunction(_getHtml, url, referer, headers, NoCookie, data, error)
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\script.common.plugin.cache\resources\lib\storage_server\StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "C:\Users\Frallan\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\utils.py", line 403, in _getHtml
                                                url = urllib_parse.quote(url, ':/%?&=')
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1286, in quote
                                                raise TypeError('None object cannot be quoted')
                                            TypeError: None object cannot be quoted
```

**Comment by DJMix-I-Can** [comment]
The fix is working on Android.

**Comment by dobbelina** [comment]
When setting the preferred maximum quality to `4K` or `Ask` in settings it works.
Gujal00 is looking into it.

**Comment by DJMix-I-Can** [comment]
You're correct. I had my settings set to 4K. Once I changed it to HD, the error occurred as well
![Perverzija](https://user-images.githubusercontent.com/35236592/170888215-e5e82f12-dc40-4d12-b6b8-37a3b7f14e16.jpg)
.

**Comment by dobbelina** [comment]
A fix has been issued.
Will be in the next 1.1.44 release https://github.com/dobbelina/repository.dobbelina/commit/f323ad3ac41cc8089c89f22bfb7b7157d5cb1f2b
