### ISSUE TITLE
RTMP playback broken

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#714]
### Bug reports:

RTMP playback with patched inputstream.rtmp no longer works.  Gives immediate error 100% of the time.

### OS environment
Android TV, Fire TV and Windows 10, using Kodi 19.3 and Cumination 1.1.34

http://paste.kodi.tv/kurixocuno

**Comment by Gujal00** [comment]
Looks like Chaturbate have stopped streaming in RTMP format.
Just to confirm inputstream.rtmp is working, try any model from the site `Naked` That site is still streaming in RTMP

**Comment by TarkusLV** [comment]
Ah, that sucks.  I don't normally use Naked, and it's not even opening for me right now to test (Fire TV and Windows), but I have no reason to doubt you.

HLS is very flakey for me on Chaturbate (which is mainly what I use Cumination for).  I guess I'll create another issue for that, assuming it's not a known issue.

Thanks.

**Comment by DJMix-I-Can** [comment]
Chaturbate works for me when using HLS. Once I switch to RTMP it fails. As for Naked, neither HLS or RTMP work because of an error. I think they changed something & it happens to be a coincidence. I created a debug file but Pastebin didn't let me post it because it said, "Pastebin’s SMART filters have detected potentially offensive or questionable content in your paste.
The content you are trying to publish has been deemed potentially offensive or questionable by our filters, because of this you’re receiving this warning.
This paste can only be published with the visibility set to "Private". So, I'm providing the actual error on here.

the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/url_dispatcher.py", line 115, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/sites/naked.py", line 54, in List
                                                       models = json.loads(data)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

**Comment by TarkusLV** [comment]
With HLS enabled in Chaturbate, sometimes the model loads right away, and sometimes I have to keep clicking on it (often 5-10 times) before it loads and streams, or I give up.  With RTMP, there was never an issue, which is why I was using it.

**Comment by Gujal00** [comment]
> As for Naked, neither HLS or RTMP work because of an error. I think they changed something & it happens to be a coincidence.

It works fine, may be dependent on location. I am unable to replicate
![image](https://i.imgur.com/IzFH7k3.png)

and plays RTMP fine
```
INFO <general>: VideoPlayer::OpenFile: rtmp://wowza-edge001.vs3.com/liveEdge/1032845-video-gpu005-mojo-eu.vs3.com.f4v app=liveEdge/1032845-video-gpu005-mojo-eu.vs3.com.f4v swfUrl=https://www.naked.com/chat/flash/live-video-player-nw2.swf pageUrl=https://www.naked.com/ playpath=mp4:1032845-video-gpu005-mojo-eu.vs3.com.f4v
```
![image](https://i.imgur.com/oIhn9RA.jpg)

**Comment by DJMix-I-Can** [comment]
You are correct. I installed a VPN to see if that was the case & it was.
