### ISSUE TITLE
Max Porn - Sites within this no longer open. 

### ISSUE THREAD

**Issue by oNeXuSo** [dobbelina/repository.dobbelina#838]
None of the sites / folders within Max Porn opens.  You can view the list of sites showing their updated thumbnail but clicking into any of them no longer works for me. If someone can redirect me on how to show log happy to provide as it does mention to refer to this when attempting to open.  I've cleared cache, uninstalled and installed the addon again but still the same.

**Comment by oNeXuSo** [comment]
I believe this is the part that's causing the error (hope this helps): 

2022-08-14 14:30:47.632 T:17804   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Error: mode pornhat.List requested argument url but it was not provided.
                                                   Traceback (most recent call last):
                                                     File "C:\Users\oinex\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\oinex\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\oinex\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 105, in dispatch
                                                       raise Exception(message)
                                                   Exception: Error: mode pornhat.List requested argument url but it was not provided.
                                                   -->End of Python script error report<--
                                                   
2022-08-14 14:30:47.713 T:17804    INFO <general>: Python interpreter stopped
2022-08-14 14:30:47.721 T:25796   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.cumination/?channel=None&keyword&mode=pornhat.List&name=Brazzers%20%5bCOLOR%20hotpink%5d5840%20videos%5b%2fCOLOR%5d&page=None&section=None&url
2022-08-14 14:30:47.722 T:2712    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/?channel=None&keyword&mode=pornhat.List&name=Brazzers%20%5bCOLOR%20hotpink%5d5840%20videos%5b%2fCOLOR%5d&page=None&section=None&url) failed

**Comment by 12asdfg12** [comment]
Website error (https://max.porn/)

**Comment by oNeXuSo** [comment]
Didn't realize this was a website issue - Thanks 12asdfg12 for clarifying.
