### ISSUE TITLE
xhamster not work

### ISSUE THREAD

**Issue by olegna66** [dobbelina/repository.dobbelina#943]
xhamster not work next/previous not appear - categories error

INFO <general>: CPythonInvoker(6, C:\Users\Win10\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py): script aborted
INFO <general>: Python interpreter stopped
INFO <general>: initializing python engine.
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'maxPages'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Win10\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\Win10\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\Win10\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 122, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\Win10\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\xhamster.py", line 91, in List
                                                       lp = jdata["maxPages"]
                                                   KeyError: 'maxPages'
                                                   -->End of Python script error report<--
                                                   
INFO <general>: Python interpreter stopped
ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.cumination/?channel=None&keyword&mode=xhamster.List&name=Italia&page=None&section=None&url=https%3a%2f%2fxhamster.com%2ftags%2fitalia%2fnewest
ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cumination/?channel=None&keyword&mode=xhamster.List&name=Italia&page=None&section=None&url=https%3a%2f%2fxhamster.com%2ftags%2fitalia%2fnewest) failed

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/f8773d3e49936a70a7e95d0620298b90b82e5157

**Comment by olegna66** [comment]
Thanks, this is working fine.
