### ISSUE TITLE
Several sites down

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#988]
Hi there,

the following sites aren't accessible anymore, or no content:
(08.03.2023)

Pornez.net
JAV Moe
OK Porn
PelisxPorno
Pornhive
Porno365
Porntube.nl
Rule34 Video
Sextube.nl
SpankBang
Xhamster.com (site forwarding issue, keeps first site when pushing forward) 
XvideoSpanish

Pls fix 😉

**Comment by dobbelina** [comment]
[fixed - javmoe, pornez, okporn](https://github.com/dobbelina/repository.dobbelina/commit/343476790cebb51362488d075845678ab6cb5fcf)

**Comment by bOuNtYhUnTeR2022** [comment]
Wow this was fast 😛👍

**Comment by 12asdfg12** [comment]
pornez related videos - it works like on the website
PelisxPorno - uses netu/hqq as video host, which doesn't work in kodi, will not be fixed
Pornhive - the website is not working
Porno365 - works for me
poldertube - fixed
porntube - fixed
sextube - fixed
12milf - fixed
Rule34 Video - Ddos-guard
SpankBang - Cloudflare

**Comment by kalebh70** [comment]
Pervzija is also down with this error EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kaleb\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 155, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\kaleb\AppData\Roaming\Kodi\addons\plugin.video.cumination\default.py", line 148, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\kaleb\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 122, in dispatch
                                                       cls.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\kaleb\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites\perverzija.py", line 160, in Play
                                                       videourl = utils.prefquality(links, sort_by=lambda x: int(x), reverse=True)
                                                     File "C:\Users\kaleb\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\utils.py", line 1233, in prefquality
                                                       vidurl = video_list[-1][1]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

**Comment by dobbelina** [comment]
[nltubes fix](https://github.com/dobbelina/repository.dobbelina/commit/2def15937e35584067f0f03624693ad15cdae251)
